# # .github/workflows/pr-analysis.yml
# name: Analyze Pull Request

# on:
#   pull_request:
#     types: [opened, synchronize, reopened]

# jobs:
#   analyze:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.x'

#     - name: Install dependencies
#       run: 
#         python -m pip install --upgrade pip
#         pip install requests
        
#     - name: Run analysis script
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         PR_NUMBER: ${{ github.event.pull_request.number }}
#         GITHUB_REPOSITORY: ${{ github.repository }}
#       run: python scripts/analyze_pr.py
